export enum ActionType {
  ADD_PROJECT_REQUEST = "add_project_request",
  ADD_PROJECT_SUCCESS = "add_project_success",
  ADD_PROJECT_ERROR = "add_project_error",
  GET_PROJECT_REQUEST = "get_project_request",
  GET_PROJECT_SUCCESS = "get_project_success",
  GET_PROJECT_ERROR = "get_project_error",
  GET_PROJECTS_REQUEST = "get_projects_request",
  GET_PROJECTS_SUCCESS = "get_projects_success",
  GET_PROJECTS_ERROR = "get_projects_error",
  UPDATE_PROJECT_SUCCESS = "update_project_success",
  UPDATE_PROJECT_ERROR = "update_project_error",
  DELETE_PROJECT_SUCCESS = "delete_project_success",
  DELETE_PROJECT_ERROR = "delete_project_error",
}
